# Python Intermediate: NumPy Basics

![caption](images/numpy-logo.jpg)
***
NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. Let's along with the basics of NumPy such as its architecture and environment. It also discusses the various array functions, types of indexing, etc.

We can install numpy by `pip install numpy`

- Main object: **`ndarray`**

<img src="images/numpy-logo.jpg" id='numpy' alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
# ndarray
***

The most important object defined in NumPy is an N-dimensional array type called ndarray. It describes the collection of items of the same type. Items in the collection can be accessed using a zero-based index.

Every item in an ndarray takes the same size of block in the memory. Each element in ndarray is an object of data-type object (called dtype).Any item extracted from ndarray object (by slicing) is represented by a Python object of one of array scalar types. An instance of ndarray class can be constructed by different array creation routines described later.

You import the function in python by calling `import numpy`. The basic ndarray is created using an array function in NumPy as follows −

In [1]:
import numpy
numpy.array

<function numpy.core.multiarray.array>

<img src="images/numpy-logo.jpg" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />
## How do I create Arrays in Python?
***
* Create an array from a regular Python list or tuple using the array function. 

* The type of the resulting array is deduced from the type of the elements in the sequences

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

In [2]:
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

array(<class 'object'>, dtype=object)

In [3]:
import numpy as np

# From list: 1d array
my_list = [10, 20, 30]
np.array(my_list)

array([10, 20, 30])

In [4]:
# From list: 2d array

list_of_lists =  [[5, 10, 15], [20, 25, 30], [35, 40, 45]]
np.array(list_of_lists)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
type(np.array(list_of_lists))

numpy.ndarray

In [6]:
#append one more list to 'list_of_lists' and convert it into numpy array



Double-click __here__ for the solution.
<!--The correct answer is: 
list_of_lists.append([10,10,10])
np.array(list_of_lists)
-->

An example of how does n-dimensional looks

## Types

![NumPy Array Types](images/numpy-types1.jpg)

`ndarray` is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:

***ndarray.ndim***
the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.

***ndarray.shape***
the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the rank, or number of dimensions,`ndim`.

***ndarray.size***
the total number of elements of the array. This is equal to the product of the elements of shape.

***ndarray.dtype***
an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

***ndarray.reshape***
Returns an array containing the same data with a new shape.

<img src="images/numpy-logo.jpg" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

## numpy.dtype
***
<br/>
The data type or dtype describes the kind of elements that are contained within the array.

* **bool**: Boolean values
<br/><br/>

* **int**: Integer values. Can be int16, int32, or int64.


* **float**: Floating point values. Can be float16, float32, or float64.
<br/><br/>


* ** string**: Text. Can be string or unicode (this distinction is greatly simplified in Python 3)

<img src="images/numpy-logo.jpg" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

***
## Let's try it ourselves!
***
### Create a vector from the list [10, 20, 30]. Print the dtype and shape.

In [34]:
my_list = [10, 20, 30]

arr = np.array(my_list)

print(arr.dtype)
print(arr.shape)

int64
(3,)


<img src="images/numpy-logo.jpg" alt="Technical-Stuff" style="width: 100px;float:left; margin-right:15px"/>
<br />

***
### Question: Create a matrix from the list of lists [[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1, 45.6]]. Print the dtype and shape. 

Double-click __here__ for the solution.
<!--The correct answer is: 
my_list = [[5.3, 10.2, 15.1], [20.4, 25.3, 30.9], [35.4, 40.1, 45.6]]
arr = np.array(my_list)
print(arr.dtype)
print(arr.shape)
-->

### Important Concepts
***
#### Rank

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. 

In the example below, the array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 6.

In [7]:
a =  np.array([[1, 2, 3,4,5,6],[7,8,9,10,11,12]]) 
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [8]:
print(a.shape)

(2, 6)


In [9]:
print(np.ndim(a))

2


# NumPy Built-in methods

## `arange`
***
arange(**[start,]** ***stop[, step,][, dtype]***) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. **[Start, Stop)** (similar to the Python **`range()`** function).

In [10]:
import numpy as np

np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## `zeros` and `ones`
***
Generate arrays of all zeros and ones

In [11]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Create zeros metrix of dim (4,5)


Double-click __here__ for the solution.
<!--The correct answer is: 
np.zeros((4,5))
-->

In [12]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [2]:
#Create ones metrix of dim(3,6)



Double-click __here__ for the solution.
<!--The correct answer is: 
np.ones((3,6))
-->

## `eye`
***
Creates an identity matrix of given size

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## `linspace`
***
Linspace: Return **evenly spaced** numbers over a specified interval.

    linspace(start, stop, num=50, endpoint=True, retstep=False)

* Will return `num` number of values
* Equally spaced samples in the closed interval [start, stop] or the half-open interval [start, stop)
* Closed or half-open interval depends on whether 'endpoint' is True or False.

In [14]:
# divide into 7 interval from 0 to 10
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

<img src="images/numpy-logo.jpg" alt="Concept-Alert" style="width: 100px;float:left; margin-right:15px"/>
<br />
## How do I generate Random Numbers?
***
<br/>
Numpy also has lots of ways to create random number arrays of given shape

- **`rand`**:

`numpy.random.rand(d0, d1, …, dn)` Create an array of the given shape and populate it with random samples from a **uniform distribution**

- **`randn`**: 

`numpy.random.randn(d0, d1, …, dn)`creates an array of specified shape and fills it with random values as per **standard normal distribution**.

If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation).

A single float randomly sampled from the distribution is returned if no argument is provided.

- **`randint`**: 

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [15]:
# random number (uniform distribution) array of shape (5, 5)

np.random.rand(3, 4)

array([[0.67899821, 0.31075501, 0.05045032, 0.71168124],
       [0.95666795, 0.69166043, 0.65514543, 0.19066398],
       [0.53759188, 0.58817927, 0.17157411, 0.91478361]])

In [16]:
# random number (standard normal distribution) array of shape (2, 3)

print (np.random.randn(2, 3))

[[ 0.86885944 -0.0203105   1.3551328 ]
 [-0.94221467 -1.09748738  0.31301171]]


In [17]:
# 10 random integers between 4 (inclusive) to 40 (exclusive)

np.random.randint(4, 40, 10)

array([ 7, 28, 13, 14,  8, 24, 11, 36,  4, 20])

In [18]:
# 10 random integers upto 50 (exclusive). This makes the start value default to 0.
# The size parameter dictates the return array shape

np.random.randint(50, size=(3,4))

array([[27, 16, 34, 31],
       [ 3, 24, 37, 43],
       [31, 42, 41, 38]])



***
Lets try to create a ndimensions array from randomly genrated numbers of (3,4), then rehape the array to (4,3)
